name: Build ROCm Wheels

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of llama-cpp-binaries to build: v0.1.0'
        default: 'v0.1.0'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version tag of llama-cpp-binaries to build: v0.1.0'
        default: 'v0.1.0'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build_wheels_rocm:
    name: ROCm Wheels
    uses: ./.github/workflows/build-wheels-rocm-full.yml
    with:
      version: ${{ inputs.version }}
      config: 'rename:1'
